# Generated by Django 5.2.1 on 2025-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spyCat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spycat",
            name="breed",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name="Breed",
        ),
    ]
